package org.dev.tequilacluster.dtos.bottling;

import jakarta.validation.constraints.NotEmpty;

import java.util.List;

/**
 * Administrator-only bulk load of SAT tax label folios (fiscal marbetes are supplied
 * externally, not generated by this system — see CLAUDE.md "Fuera de alcance"). Lets the
 * catalog be seeded via Postman before a bottling batch is created, instead of a direct SQL
 * insert.
 */
public record TaxLabelBulkCreateRequest(
        @NotEmpty List<String> folios
) {
}
